# Generated by Django 2.2.24 on 2022-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0025_auto_20220305_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time for this workflow is deactivated.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time for this workflow is activated.', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time for this state is deactivated.', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time for this state is activated.', null=True, verbose_name='Start Date'),
        ),
    ]
