# Generated by Django 2.2.24 on 2022-03-07 16:21

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0027_auto_20220306_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='internal_name',
            field=models.CharField(db_index=True, error_messages={'required': 'Internal name is Required'}, help_text='This value will be used by other apps to reference this workflow. Can only contain letters, numbers, and underscores.', max_length=255, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+\\Z'), "Enter a valid 'internal name' consisting of letters, numbers, and underscores.", 'invalid')], verbose_name='Internal name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='label',
            field=models.CharField(error_messages={'required': 'Label is Required'}, help_text='A short text to describe the workflow.', max_length=255, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='label',
            field=models.TextField(error_messages={'required': 'Label is Required'}, help_text='A short text to describe the workflow state.', verbose_name='Label'),
        ),
    ]
