# Generated by Django 2.2.24 on 2022-03-16 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_states', '0028_auto_20220307_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='internal_name',
            field=models.CharField(db_index=True, help_text='This value will be used by other apps to reference this workflow. Can only contain letters, numbers, and underscores.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+\\Z'), "Enter a valid 'internal name' consisting of letters, numbers, and underscores.", 'invalid')], verbose_name='Internal name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='label',
            field=models.CharField(help_text='A short text to describe the workflow.', max_length=255, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='label',
            field=models.TextField(help_text='A short text to describe the workflow state.', verbose_name='Label'),
        ),
    ]
