# Generated by Django 2.2.24 on 2022-03-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_auto_20211023_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocaleprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('bg', 'Bulgarian'), ('bs', 'Bosnian'), ('cs', 'Czech'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('es-pr', 'Spanish (Puerto Rico)'), ('fa', 'Persian'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('lv', 'Latvian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese (Brazil)'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sl', 'Slovenian'), ('th', 'Thai'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Chinese (Simplified)')], max_length=8, verbose_name='Language'),
        ),
    ]
