# Generated by Django 2.2.24 on 2022-03-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20210823_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='default',
            field=models.BooleanField(default=False, help_text='Set this theme to default theme.', verbose_name='Default'),
        ),
    ]
