# Generated by Django 2.2.24 on 2022-03-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0019_auto_20200819_0852'),
        ('appearance', '0006_auto_20220318_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='font_asset', to='converter.Asset', verbose_name='Font file'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_asset', to='converter.Asset', verbose_name='Logo file'),
        ),
    ]
