# Generated by Django 2.2.24 on 2022-03-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_auto_20220319_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='header_bg',
            field=models.CharField(blank=True, help_text='The color of background on header components.', max_length=7, verbose_name='[Header] Text Background Color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='header_text',
            field=models.CharField(blank=True, help_text='The color of text on header components.', max_length=7, verbose_name='[Header] Text Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='default',
            field=models.BooleanField(default=False, help_text='Set this theme to default theme.', verbose_name='Default Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the different user interface elements.', verbose_name='Stylesheet (Advanced)'),
        ),
    ]
