# Generated by Django 2.2.24 on 2022-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0008_auto_20220321_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='lpanel_collapse_btn_bg',
            field=models.CharField(blank=True, help_text='The color of collapse button background on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_bg',
            field=models.CharField(blank=True, help_text='The color of background on header components.', max_length=7, verbose_name='[Header] Background Color'),
        ),
    ]
