# Generated by Django 2.2.24 on 2022-03-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0010_auto_20220321_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='lpanel_collapse_btn_bg_hover',
            field=models.CharField(blank=True, help_text='(Hover action)The background color of collapse button on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Background Color(Hover action)'),
        ),
    ]
