# Generated by Django 2.2.24 on 2022-03-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0011_theme_lpanel_collapse_btn_bg_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='lpanel_collapse_btn_text_hover',
            field=models.CharField(blank=True, help_text='(Hover action)The text color of collapse button on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Text Color(Hover action)'),
        ),
    ]
