# Generated by Django 2.2.24 on 2022-03-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0012_theme_lpanel_collapse_btn_text_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='lpanel_bg',
            field=models.CharField(blank=True, help_text='The background color on left panel components.', max_length=7, verbose_name='[Left Panel] Background Color'),
        ),
    ]
