# Generated by Django 2.2.24 on 2022-03-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0013_theme_lpanel_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='lpanel_collapsed_btn_bg_hover',
            field=models.CharField(blank=True, help_text='(Active+Hover action)The background color of collapsed button on left panel.', max_length=7, verbose_name='[Left Panel] Collapsed Button Background Color(Active+Hover action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='lpanel_collapsed_btn_text',
            field=models.CharField(blank=True, help_text='(Active action)The text color of collapsed button on left panel.', max_length=7, verbose_name='[Left Panel] Collapsed Button Text Color(Active action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='lpanel_collapsed_panel_bg',
            field=models.CharField(blank=True, help_text='(Active action)The background color of collapsed panel on left panel.', max_length=7, verbose_name='[Left Panel] Collapsed Panel Background Color(Active action)'),
        ),
    ]
