# Generated by Django 2.2.24 on 2022-03-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0015_auto_20220321_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='rnav_bg_hover',
            field=models.CharField(blank=True, help_text='(Hover action)The background color of button on right navbar.', max_length=7, verbose_name='[Right Navbar] Button Background Color(Hover action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='rnav_ex_bg_hover',
            field=models.CharField(blank=True, help_text='(Expanded+Hover Action)The background color of panel on right navbar menu list when hover.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Background Color(Expanded+Hover action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='rnav_ex_text_hover',
            field=models.CharField(blank=True, help_text='(Expanded+Hover Action)The text color of panel on right navbar menu list when hover.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Text Color(Expanded+Hover action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='rnav_panelex_bg',
            field=models.CharField(blank=True, help_text='(Expanded Action)The background color of panel on right navbar menu list.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Background Color(Expanded action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='rnav_panelex_text',
            field=models.CharField(blank=True, help_text='(Expanded Action)The text color of panel on right navbar menu list.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Text Color(Expanded action)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='rnav_text_hover',
            field=models.CharField(blank=True, help_text='(Hover action)The text color of button on right navbar.', max_length=7, verbose_name='[Right Navbar] Button Text Color(Hover action)'),
        ),
    ]
