# Generated by Django 2.2.24 on 2022-03-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0016_auto_20220321_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='header_text_brand',
            field=models.CharField(blank=True, help_text='The heading text on header components.', max_length=20, verbose_name='Heading Text'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='The background color on page body.', max_length=7, verbose_name='[Body] Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body_block',
            field=models.CharField(blank=True, default='#ECF0F1', help_text='The block color on page body.', max_length=7, verbose_name='[Body] Block Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body_link_hover',
            field=models.CharField(blank=True, default='#0a5286', help_text='(Hover action)The link color on page body.', max_length=7, verbose_name='[Body] Link Text Color (Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body_primary_btn',
            field=models.CharField(blank=True, default='#0F75BD', help_text='The background color of primary button on page body.', max_length=7, verbose_name='[Body] Primary Button Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body_text',
            field=models.CharField(blank=True, default='#0a5286', help_text='The text color on page body.', max_length=7, verbose_name='[Body] Text Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='The background color on header components.', max_length=7, verbose_name='[Header] Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_text',
            field=models.CharField(blank=True, default='#0F75BD', help_text='The text color on header components.', max_length=7, verbose_name='[Header] Text Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='The background color on left panel components.', max_length=7, verbose_name='[Left Panel] Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapse_btn_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='The background color of collapse button on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Background Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapse_btn_bg_hover',
            field=models.CharField(blank=True, default='#0F75BD', help_text='(Hover action)The background color of collapse button on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Background Color(Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapse_btn_text',
            field=models.CharField(blank=True, default='#0F75BD', help_text='The text color of collapse button on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Text Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapse_btn_text_hover',
            field=models.CharField(blank=True, default='#ffffff', help_text='(Hover action)The text color of collapse button on left panel.', max_length=7, verbose_name='[Left Panel] Collapse Button Text Color(Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapsed_btn_bg_hover',
            field=models.CharField(blank=True, default='#0F75BD', help_text='(Active+Hover action)The background color of collapsed button on left panel.', max_length=7, verbose_name='[Left Panel] Collapsed Button Background Color(Active+Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapsed_btn_text',
            field=models.CharField(blank=True, default='#ffffff', help_text='(Active action)The text color of collapsed button on left panel.', max_length=7, verbose_name='[Left Panel] Collapsed Button Text Color(Active action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lpanel_collapsed_panel_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='(Active action)The background color of collapsed panel on left panel.', max_length=7, verbose_name='[Left Panel] Collapsed Panel Background Color(Active action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rnav_bg_hover',
            field=models.CharField(blank=True, default='#0F75BD', help_text='(Hover action)The background color of button on right navbar.', max_length=7, verbose_name='[Right Navbar] Button Background Color(Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rnav_ex_bg_hover',
            field=models.CharField(blank=True, default='#0F75BD', help_text='(Expanded+Hover Action)The background color of panel on right navbar menu list when hover.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Background Color(Expanded+Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rnav_ex_text_hover',
            field=models.CharField(blank=True, default='#ffffff', help_text='(Expanded+Hover Action)The text color of panel on right navbar menu list when hover.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Text Color(Expanded+Hover action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rnav_panelex_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='(Expanded Action)The background color of panel on right navbar menu list.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Background Color(Expanded action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rnav_panelex_text',
            field=models.CharField(blank=True, default='#0F75BD', help_text='(Expanded Action)The text color of panel on right navbar menu list.', max_length=7, verbose_name='[Right Navbar] Expanded Panel Text Color(Expanded action)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rnav_text_hover',
            field=models.CharField(blank=True, default='#0F75BD', help_text='(Hover action)The text color of button on right navbar.', max_length=7, verbose_name='[Right Navbar] Button Text Color(Hover action)'),
        ),
    ]
