# Generated by Django 2.2.24 on 2022-03-22 01:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0019_auto_20200819_0852'),
        ('appearance', '0017_auto_20220322_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font_header_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='font_header_asset', to='converter.Asset', verbose_name='Header font file'),
        ),
        migrations.AddField(
            model_name='theme',
            name='header_text_brand_size',
            field=models.PositiveIntegerField(default=10, help_text='The font size of heading text on header components.', validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(36)], verbose_name='Heading Text Font Size'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_text_brand',
            field=models.CharField(blank=True, help_text='The heading text on header components.', max_length=26, verbose_name='Heading Text'),
        ),
    ]
