# Generated by Django 2.2.24 on 2022-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0077_favoritedocumentproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, default='tha', help_text='The primary language in the document.', max_length=8, verbose_name='Language'),
        ),
    ]
